# Data Sources Configuration
# Multi-Market Correlation Engine

# Yahoo Finance Data Sources
yahoo_finance:
  equities:
    global_indices:
      - "^GSPC"    # S&P 500
      - "^IXIC"    # NASDAQ
      - "^DJI"     # Dow Jones
      - "^FTSE"    # FTSE 100
      - "^GDAXI"   # DAX
      - "^N225"    # Nikkei 225
      - "^HSI"     # Hang Seng
    sector_etfs:
      - "XLF"      # Financial Select Sector SPDR Fund
      - "XLK"      # Technology Select Sector SPDR Fund
      - "XLE"      # Energy Select Sector SPDR Fund
      - "XLI"      # Industrial Select Sector SPDR Fund
      - "XLV"      # Health Care Select Sector SPDR Fund
  
  commodities:
    - "GC=F"       # Gold Futures
    - "CL=F"       # Crude Oil Futures
    - "SI=F"       # Silver Futures
    - "NG=F"       # Natural Gas Futures
    - "ZC=F"       # Corn Futures
    - "ZW=F"       # Wheat Futures
  
  bonds:
    - "^TNX"       # 10-Year Treasury Yield
    - "^FVX"       # 5-Year Treasury Yield
    - "^TYX"       # 30-Year Treasury Yield
    - "TLT"        # 20+ Year Treasury Bond ETF
    - "IEF"        # 7-10 Year Treasury Bond ETF
    - "SHY"        # 1-3 Year Treasury Bond ETF
  
  currencies:
    - "EURUSD=X"   # EUR/USD
    - "GBPUSD=X"   # GBP/USD
    - "USDJPY=X"   # USD/JPY
    - "USDCHF=X"   # USD/CHF
    - "AUDUSD=X"   # AUD/USD
    - "USDCAD=X"   # USD/CAD

# Cryptocurrency Data Sources
crypto:
  coingecko:
    base_url: "https://api.coingecko.com/api/v3"
    coins:
      - "bitcoin"
      - "ethereum"
      - "binancecoin"
      - "cardano"
      - "solana"
      - "polkadot"
      - "chainlink"
      - "litecoin"
      - "avalanche-2"
      - "polygon"
    vs_currency: "usd"
    days: "max"
  
  ccxt:
    exchanges:
      - "binance"
      - "coinbase"
      - "kraken"
    symbols:
      - "BTC/USDT"
      - "ETH/USDT"
      - "BNB/USDT"
      - "ADA/USDT"
      - "SOL/USDT"

# FRED API (Federal Reserve Economic Data)
fred:
  api_key_env: "FRED_API_KEY"
  series:
    macro_indicators:
      - "GDP"         # Gross Domestic Product
      - "CPIAUCSL"    # Consumer Price Index
      - "UNRATE"      # Unemployment Rate
      - "FEDFUNDS"    # Federal Funds Rate
      - "DGS10"       # 10-Year Treasury Rate
      - "DEXUSEU"     # US/Euro Exchange Rate
      - "VIXCLS"      # VIX Volatility Index
    
    economic_indicators:
      - "INDPRO"      # Industrial Production Index
      - "HOUST"       # Housing Starts
      - "PAYEMS"      # Total Nonfarm Payrolls
      - "UMCSENT"     # University of Michigan Consumer Sentiment
      - "NAPM"        # ISM Manufacturing PMI

# Data Collection Settings
collection:
  frequency:
    daily: ["equities", "commodities", "bonds", "currencies", "crypto"]
    weekly: ["fred_high_freq"]
    monthly: ["fred_low_freq"]
  
  historical_period:
    start_date: "2010-01-01"  # Default start date for historical data
    min_observations: 252     # Minimum trading days required
  
  data_quality:
    max_missing_pct: 0.05     # Maximum 5% missing data allowed
    outlier_threshold: 5      # Standard deviations for outlier detection
    min_price: 0.01          # Minimum price to avoid penny stock issues

# API Rate Limiting
rate_limits:
  yahoo_finance:
    requests_per_minute: 2000
    delay_between_requests: 0.1
  
  coingecko:
    requests_per_minute: 10   # Free tier limit
    delay_between_requests: 6
  
  fred:
    requests_per_minute: 120
    delay_between_requests: 0.5

# Data Storage
storage:
  database:
    type: "sqlite"
    name: "market_data.db"
    location: "data/market_data.db"
  
  backup:
    enabled: true
    frequency: "daily"
    retention_days: 30
    location: "data/backups/"

# Error Handling
error_handling:
  max_retries: 3
  retry_delay: 5  # seconds
  fallback_sources:
    yahoo_finance: ["alpha_vantage", "quandl"]
    coingecko: ["coinmarketcap", "cryptocompare"] 