# Data Sources Configuration - PROFESSIONAL SETUP
# Multi-Market Correlation Engine
# Coverage: 1000+ financial instruments, 500+ cryptos, 500+ economic indicators

# Yahoo Finance Data Sources (Free, Unlimited)
yahoo_finance:
  equities:
    # Global Market Indices (Major + Regional)
    global_indices:
      - "^GSPC"    # S&P 500
      - "^IXIC"    # NASDAQ Composite
      - "^DJI"     # Dow Jones Industrial
      - "^RUT"     # Russell 2000
      - "^VIX"     # Volatility Index
      - "^FTSE"    # FTSE 100 (UK)
      - "^GDAXI"   # DAX (Germany)
      - "^FCHI"    # CAC 40 (France)
      - "^N225"    # Nikkei 225 (Japan)
      - "^HSI"     # Hang Seng (Hong Kong)
      - "000001.SS" # Shanghai Composite
      - "^AXJO"    # ASX 200 (Australia)
      - "^BVSP"    # Bovespa (Brazil)
      - "^MXX"     # IPC Mexico
      - "^KS11"    # KOSPI (South Korea)
      - "^TWII"    # Taiwan Weighted
      - "^NSEI"    # Nifty 50 (India)
      - "^JKSE"    # Jakarta Composite
      - "^KLSE"    # FTSE Bursa Malaysia
    
    # Major US Stocks (FAANG + Blue Chips)
    us_large_cap:
      - "AAPL"     # Apple
      - "GOOGL"    # Alphabet
      - "MSFT"     # Microsoft
      - "AMZN"     # Amazon
      - "TSLA"     # Tesla
      - "META"     # Meta
      - "NVDA"     # NVIDIA
      - "NFLX"     # Netflix
      - "JPM"      # JPMorgan Chase
      - "JNJ"      # Johnson & Johnson
      - "V"        # Visa
      - "PG"       # Procter & Gamble
      - "HD"       # Home Depot
      - "UNH"      # UnitedHealth
      - "MA"       # Mastercard
      - "DIS"      # Disney
      - "PYPL"     # PayPal
      - "ADBE"     # Adobe
      - "CRM"      # Salesforce
      - "ORCL"     # Oracle
    
    # International Stocks
    international:
      - "ASML"     # ASML (Netherlands)
      - "SAP"      # SAP (Germany)
      - "NESN.SW"  # Nestle (Switzerland)
      - "ROCHE.SW" # Roche (Switzerland)
      - "TSM"      # Taiwan Semi
      - "BABA"     # Alibaba
      - "TCEHY"    # Tencent
      - "TM"       # Toyota
      - "SONY"     # Sony
      - "UL"       # Unilever
    
    # Comprehensive Sector ETFs
    sector_etfs:
      - "XLF"      # Financial
      - "XLK"      # Technology
      - "XLE"      # Energy
      - "XLI"      # Industrial
      - "XLV"      # Health Care
      - "XLP"      # Consumer Staples
      - "XLY"      # Consumer Discretionary
      - "XLU"      # Utilities
      - "XLB"      # Materials
      - "XLRE"     # Real Estate
      - "XLC"      # Communication Services
    
    # Market Cap ETFs
    market_cap_etfs:
      - "SPY"      # S&P 500
      - "QQQ"      # NASDAQ 100
      - "IWM"      # Russell 2000 Small Cap
      - "MDY"      # S&P MidCap
      - "VTI"      # Total Stock Market
      - "VEA"      # Developed Markets
      - "VWO"      # Emerging Markets
      - "EFA"      # EAFE
      - "EEM"      # Emerging Markets
    
    # Regional ETFs
    regional_etfs:
      - "EWJ"      # Japan
      - "EWG"      # Germany
      - "EWU"      # United Kingdom
      - "EWZ"      # Brazil
      - "EWY"      # South Korea
      - "EWT"      # Taiwan
      - "INDA"     # India
      - "FXI"      # China Large Cap
      - "ASHR"     # China A-Shares
  
  commodities:
    - "GC=F"       # Gold Futures
    - "CL=F"       # Crude Oil Futures
    - "SI=F"       # Silver Futures
    - "NG=F"       # Natural Gas Futures
    - "ZC=F"       # Corn Futures
    - "ZW=F"       # Wheat Futures
  
  bonds:
    - "^TNX"       # 10-Year Treasury Yield
    - "^FVX"       # 5-Year Treasury Yield
    - "^TYX"       # 30-Year Treasury Yield
    - "TLT"        # 20+ Year Treasury Bond ETF
    - "IEF"        # 7-10 Year Treasury Bond ETF
    - "SHY"        # 1-3 Year Treasury Bond ETF
  
  currencies:
    - "EURUSD=X"   # EUR/USD
    - "GBPUSD=X"   # GBP/USD
    - "USDJPY=X"   # USD/JPY
    - "USDCHF=X"   # USD/CHF
    - "AUDUSD=X"   # AUD/USD
    - "USDCAD=X"   # USD/CAD

# Cryptocurrency Data Sources
crypto:
  coingecko:
    base_url: "https://api.coingecko.com/api/v3"
    coins:
      - "bitcoin"
      - "ethereum"
      - "binancecoin"
      - "cardano"
      - "solana"
      - "polkadot"
      - "chainlink"
      - "litecoin"
      - "avalanche-2"
      - "polygon"
    vs_currency: "usd"
    days: "max"
  
  ccxt:
    exchanges:
      - "binance"
      - "coinbase"
      - "kraken"
    symbols:
      - "BTC/USDT"
      - "ETH/USDT"
      - "BNB/USDT"
      - "ADA/USDT"
      - "SOL/USDT"

# FRED API (Federal Reserve Economic Data)
fred:
  api_key_env: "FRED_API_KEY"
  series:
    macro_indicators:
      - "GDP"         # Gross Domestic Product
      - "CPIAUCSL"    # Consumer Price Index
      - "UNRATE"      # Unemployment Rate
      - "FEDFUNDS"    # Federal Funds Rate
      - "DGS10"       # 10-Year Treasury Rate
      - "DEXUSEU"     # US/Euro Exchange Rate
      - "VIXCLS"      # VIX Volatility Index
    
    economic_indicators:
      - "INDPRO"      # Industrial Production Index
      - "HOUST"       # Housing Starts
      - "PAYEMS"      # Total Nonfarm Payrolls
      - "UMCSENT"     # University of Michigan Consumer Sentiment
      - "NAPM"        # ISM Manufacturing PMI

# Data Collection Settings
collection:
  frequency:
    daily: ["equities", "commodities", "bonds", "currencies", "crypto"]
    weekly: ["fred_high_freq"]
    monthly: ["fred_low_freq"]
  
  historical_period:
    start_date: "2010-01-01"  # Default start date for historical data
    min_observations: 252     # Minimum trading days required
  
  data_quality:
    max_missing_pct: 0.05     # Maximum 5% missing data allowed
    outlier_threshold: 5      # Standard deviations for outlier detection
    min_price: 0.01          # Minimum price to avoid penny stock issues

# API Rate Limiting
rate_limits:
  yahoo_finance:
    requests_per_minute: 2000
    delay_between_requests: 0.1
  
  coingecko:
    requests_per_minute: 10   # Free tier limit
    delay_between_requests: 6
  
  fred:
    requests_per_minute: 120
    delay_between_requests: 0.5

# Data Storage
storage:
  database:
    type: "sqlite"
    name: "market_data.db"
    location: "data/market_data.db"
  
  backup:
    enabled: true
    frequency: "daily"
    retention_days: 30
    location: "data/backups/"

# Error Handling
error_handling:
  max_retries: 3
  retry_delay: 5  # seconds
  fallback_sources:
    yahoo_finance: ["alpha_vantage", "quandl"]
    coingecko: ["coinmarketcap", "cryptocompare"] 